# Development credentials

active_record_encryption:
  primary_key: ul38X5wlFcyiRg0zv4QYcTg9QQDfyhgp
  deterministic_key: Z2gRXnekFfKdxGqMsyIMQYEK6QzAoyAY
  key_derivation_salt: tuH1ZIl7hyLZAQkDqIosnjZgOw8ERg5M
